services:
  # Web service for the 2D to 3D converter tool
  - type: web
    name: ego-2d-to-3d-converter
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    plan: starter
    # Uncomment the following if you need a database
    # databases:
    #  - name: ego_converter_db
    #    plan: starter
