services:
  # Web service for the 2D to 3D converter tool
  - type: web
    name: ego-2d-to-3d-converter
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    plan: starter
    # Uncomment the following if you need a database
    # databases:
    #  - name: ego_converter_db
    #    plan: starter

# Static site for documentation (optional)
  - type: web
    name: ego-converter-docs
    env: static
    buildCommand: npm run build-docs
    staticPublishPath: ./docs-build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
    plan: free
